// <auto-generated />
using System;
using EshopApp.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EshopApp.Persistence.Migrations
{
    /// <summary>
    /// Model snapshot for the application's database context, used by EF Core to keep track of the current model.
    /// </summary>
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        /// <summary>
        /// Builds the current model for the application's database context, defining entities, relationships, and schema configuration.
        /// </summary>
        /// <param name="modelBuilder">The builder used to construct the model.</param>
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // ...existing code...
#pragma warning restore 612, 618
        }
    }
}
